---
title: "表格3"
author: "lavaan"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo     = FALSE,
    warning  = FALSE, 
    message  = FALSE,
    fig.asp  = 0.618,
    dpi      = 300
)
options(digits = 3)
```



```{r}
library(tidyverse)
library(gtsummary)

rawdf <- haven::read_sav("./data/Liminal_Experience.sav") %>% 
  drop_na()

sjPlot::view_df(rawdf)
```




```{r}
d2 <- rawdf %>% 
  rowwise() %>% 
  mutate(
    Ambient  = mean(c_across(num_range("Ambient", 1:4))),
    Space    = mean(c_across(num_range("Space",   1:6))),
    Signs    = mean(c_across(num_range("Signs",   1:6)))
  ) %>% 
  ungroup() %>% 
  select(
    Ambient, Space, Signs,
    starts_with("Social"),
    starts_with("Symbol"),
    starts_with("Nature")
  )
```



```{r}
library(lavaan)

model <- '

  Physical_tourscape =~ Ambient + Space + Signs 
  Social_tourscape   =~ Social1 + Social2 + Social3 + Social4 + Social5
  Socially_symbolic_tourscape =~ Symbol1 + Symbol2 + Symbol3
  Natural_tourscape =~ Nature1 + Nature2 + Nature3

'

fit_cfa2 <- cfa(model, data = d2)
```



# 表3

```{r}
d3 <- rawdf %>% 
  rowwise() %>% 
  mutate(
    Ambient  = mean(c_across(num_range("Ambient", 1:4))),
    Space    = mean(c_across(num_range("Space",   1:6))),
    Signs    = mean(c_across(num_range("Signs",   1:6)))
  ) %>% 
  ungroup() %>% 
  transmute(
    Physical_tourscape  = Ambient + Space + Signs,
    Social_tourscape    = Social1 + Social2 + Social3 + Social4 + Social5,
    Socially_symbolic_tourscape = Symbol1 + Symbol2 + Symbol3,
    Natural_tourscape   = Nature1 + Nature2 + Nature3
 )
```


```{r}
d3 %>% 
  summarise(
    across(everything(), list(Mean = mean, SD = sd))
  ) %>% 
  pivot_longer(
    cols = everything(),
    names_to = c("variable", ".value"),
    names_pattern = "(.*)_(Mean|SD)"
  ) %>% 

  left_join(
    d3 %>% 
      corrr::correlate(
        diagonal = semTools::AVE(fit_cfa2) %>% sqrt()
      ) %>% 
      corrr::shave(),
    by = join_by("variable" == "term")
  ) %>%  
  set_names(c(" ", "Mean", "SD", "1", "2", "3", "4")) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::autofit() %>% 
  flextable::add_footer_lines(
    "Note: The bold diagonal elements are square roots of AVE for each construct. Below diagonal elements are the correlations between constructs.")
```


