---
title: "表格3"
author: "lavaan"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo     = FALSE,
    warning  = FALSE, 
    message  = FALSE,
    fig.asp  = 0.618,
    dpi      = 300
)
options(digits = 3)
```



```{r}
library(tidyverse)
library(gtsummary)

rawdf <- haven::read_sav("./data/Liminal_Experience.sav") %>% 
  drop_na()

sjPlot::view_df(rawdf)
```




# 表3

```{r}
library(lavaan)

model <- '

 # first order construct
   Ambient  =~ Ambient1 + Ambient2 + Ambient3 + Ambient4
   Space    =~ Space1 + Space2 + Space3 + Space4 + Space5 + Space6
   Signs    =~ Signs1 + Signs2 + Signs3 + Signs4 + Signs5 + Signs6

   Social_tourscape   =~ Social1 + Social2 + Social3 + Social4 + Social5
   Socially_symbolic_tourscape =~ Symbol1 + Symbol2 + Symbol3
   Natural_tourscape =~ Nature1 + Nature2 + Nature3

 # second order construct
   Physical_tourscape  =~ Ambient + Space + Signs

'

fit_cfa3 <- cfa(model, data = rawdf)
```


```{r}
constructs <- c(
    "Physical_tourscape",
    "Social_tourscape",
    "Socially_symbolic_tourscape",
    "Natural_tourscape"
  )
```


```{r, eval=FALSE}
# semTools::AVE 函数并不直接提供对于二阶因子的AVE的计算
AVE  <- semTools::AVE(fit_cfa3) 

# waiting
```




```{r}
# 构念之间的相关系数矩阵
fit_cfa3 %>% 
  lavInspect( what = "cor.lv") %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "name") %>% 
  filter(name %in% constructs) %>%
  select(name, any_of(constructs)) %>% 
  arrange(factor(name, levels = constructs)) %>% 
  set_names(c(" ", "1", "2", "3", "4")) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::autofit() %>% 
  flextable::add_footer_lines(
    "Note: The bold diagonal elements are square roots of AVE for each construct. Below diagonal elements are the correlations between constructs.")
```





