---
title: "表格6"
author: "lavaan"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo     = FALSE,
    warning  = FALSE, 
    message  = FALSE,
    fig.asp  = 0.618,
    dpi      = 300
)
options(digits = 3)
```


```{r}
library(tidyverse)
library(gtsummary)

rawdf <- haven::read_sav("./data/Liminal_Experience.sav") %>% 
  drop_na()

sjPlot::view_df(rawdf)
```


# 表6


```{r}
d6 <- rawdf %>% 
  select(ex1:ex18) 
```


```{r}
library(lavaan)

model_cfa <- '

  romance_and_relax =~ ex1 + ex11 + ex14 + ex2 + ex5 + ex15 + ex4
  chance_encounter  =~ ex10 + ex9 + ex8 + ex6 + ex7
  sense_of_loss     =~ ex17 + ex18 + ex16 
  aberration        =~ ex3 + ex13 + ex12
  
'

fit_cfa6 <- cfa(model = model_cfa, data = d6) 
```


```{r}
fit_cfa6 %>% 
  semTools::discriminantValidity() %>%  
  select(lhs, rhs, est, ci.lower, ci.upper) %>%
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::autofit()
```



