---
title: "表格1"
author: "lavaan"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo     = FALSE,
    warning  = FALSE, 
    message  = FALSE,
    fig.asp  = 0.618,
    dpi      = 300
)
options(digits = 3)
```



```{r}
library(tidyverse)

rawdf <- haven::read_sav("./data/Liminal_Experience.sav") %>% 
  drop_na() %>%
  filter(gender %in% c(1, 2)) %>%
  filter(edu %in% c(1, 2, 3))
```



# 表1

```{r}

d1 <- rawdf %>%
  select(gender, age, edu, income, time) %>%
  mutate(
    gender = factor(gender,
      levels = c(1, 2),
      labels = c("male", "female")
    ),
    age = factor(age,
      levels = c(1, 2, 3, 4),
      labels = c(
        "under 20",
        "21-30",
        "31-40",
        "above 41"
      )
    ),
    edu = factor(edu,
      levels = c(1, 2, 3),
      labels = c(
        "senior high school and below",
        "university",
        "master and above"
      )
    ),
    income = factor(income,
      levels = c(1, 2, 3, 4, 5),
      labels = c(
        "under 1500",
        "1500-3000",
        "3001-5000",
        "5001-7500",
        "above 7501"
      )
    ),
    time = factor(time,
      levels = c(1, 2, 3, 4),
      labels = c(
        "1",
        "2-3",
        "4-5",
        "> 6"
      )
    )
  )


```


## 方法1
```{r}
library(gtsummary)
d1 %>%
  tbl_summary(
    statistic = list(all_categorical() ~ "{n} ({p}%)")
  )
```


## 方法2

```{r}
library(scales)

d1 %>% 
  pivot_longer(cols = everything()) %>% 
  summarise(Frequency = n(), .by = c(name, value) ) %>% 
  mutate(
    Percent = scales::label_percent(accuracy = 0.01)(Frequency/sum(Frequency)), 
    .by = name
  ) %>% 
  arrange(name, value) %>% 
  flextable::as_grouped_data(groups = "name") %>% 
  flextable::flextable() %>% 
  flextable::autofit() %>% 
  flextable::colformat_double(j = 4, digits = 3)
```

